openapi: 3.0.3
info:
  title: client_service
  version: 1.0.0
  description: client_service_api
servers:
  - url: /api/v1/
    description: Базовый URL-префикс
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
paths:
  /clients:
    post:
      summary: Создание нового клиента
      operationId: createClient
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: 'ClientCreateRequest.yaml#/ClientCreateRequest'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: 'ClientResponse.yaml#/ClientResponse'
        '400':
          description: Невалидные данные
          content:
            application/json:
              schema:
                $ref: 'ErrorCode.yaml#/ResponseCode'
              example:
                errorCode: BAD_REQUEST
                errorDescription: "Невалидные данные"
                statusCode: 400
        '409':
          description: Клиент с таким mdmId уже существует
          content:
            application/json:
              schema:
                $ref: 'ErrorCode.yaml#/ResponseCode'
              example:
                errorCode: CONFLICT
                errorDescription: "Клиент с таким mdmId уже существует"
                statusCode: 409


    get:
      summary: Поиск клиентов с пагинацией
      operationId: getAllClients
      parameters:
        - name: page
          in: query
          required: false
          schema:
            type: integer
            default: 0
        - name: size
          in: query
          required: false
          schema:
            type: integer
            default: 20
        - name: fullName
          in: query
          required: false
          schema:
            type: string
        - name: mdmId
          in: query
          required: false
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: 'GetClients.yaml#/GetClients'


  /clients/{clientId}:
    get:
      summary: Получение клиента по ID
      operationId: getClientById
      parameters:
        - name: clientId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: 'ClientResponse.yaml#/ClientResponse'
        '404':
          description: Клиент не найден
          content:
            application/json:
              schema:
                $ref: 'ErrorCode.yaml#/ResponseCode'
              example:
                errorCode: NOT_FOUND
                errorDescription: "Клиент не найден"
                statusCode: 404


    put:
      summary: Обновление клиента
      operationId: updateClient
      parameters:
        - name: clientId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: 'PutClientById.yaml#/PutClientById'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: 'ClientResponse.yaml#/ClientResponse'
        '400':
          description: Невалидные данные
          content:
            application/json:
              schema:
                $ref: 'ErrorCode.yaml#/ResponseCode'
              example:
                errorCode: BAD_REQUEST
                errorDescription: "Невалидные данные"
                statusCode: 400
        '404':
          description: Клиент не найден
          content:
            application/json:
              schema:
                $ref: 'ErrorCode.yaml#/ResponseCode'
              example:
                errorCode: NOT_FOUND
                errorDescription: "Клиент не найден"
                statusCode: 404


    delete:
      summary: Удаление клиента
      operationId: deleteClient
      parameters:
        - name: clientId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '204':
          description: Клиент удален
        '404':
          description: NOT_FOUND - клиент не найден
          content:
            application/json:
              schema:
                $ref: 'ErrorCode.yaml#/ResponseCode'
              example:
                errorCode: NOT_FOUND
                errorDescription: "Клиент не найден"
                statusCode: 404
        '409':
          description: CONFLICT - у клиента есть активные счета
          content:
            application/json:
              schema:
                $ref: 'ErrorCode.yaml#/ResponseCode'
              example:
                errorCode: CONFLICT
                errorDescription: "У клиента есть активные счета"
                statusCode: 409


  /clients/{clientId}/exists:
    get:
      summary: Проверка существования клиента
      operationId: existsClient
      parameters:
        - name: clientId
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: 'ExistsClientResponse.yaml#/ExistsClientResponse'
        '404':
          description: NOT_FOUND
          content:
            application/json:
              schema:
                $ref: 'ExistsClientResponse.yaml#/ExistsClientResponse'